const state={models:[],summary:null,runtime:null,history:[],streamTimer:null,streamResolve:null,activeArticle:null,abortController:null,stopped:false,busy:false,requestId:0,runtimeRequest:0,lastInference:{},drawerTrigger:null};
const $=selector=>document.querySelector(selector);
const welcomeMarkup=$('#welcome').outerHTML;
const escapeHtml=value=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
const percent=value=>`${Math.round(Number(value)*100)}%`;

async function fetchJSON(url,options={}){const response=await fetch(url,options);const data=await response.json();if(!response.ok){const error=new Error(data.error||'Request failed');error.payload=data;throw error}return data}

async function initialize(){const [models,summary,runtime]=await Promise.all([fetchJSON('/api/models'),fetchJSON('/api/summary'),fetchJSON('/api/runtime')]);state.models=models;state.summary=summary;state.runtime=runtime;renderModels(false);renderRuntime(runtime);renderResearch(summary.results);updateGuardLabel();updateSearchLabel();updateSessionCaption();if(models.some(model=>model.loading))pollModelStatus()}
async function pollModelStatus(){for(let attempt=0;attempt<60;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));try{state.models=await fetchJSON('/api/models');renderModels(true);if(!state.models.some(model=>model.loading))break}catch{}}}
function renderModels(preserve=true){const select=$('#model-select'),previous=preserve?select.value:'';select.innerHTML=state.models.map(model=>{const suffix=model.ready?' · ready':model.loading?' · loading':model.available?' · installed':' · offline';return `<option value="${model.id}">${escapeHtml(model.name+suffix)}</option>`}).join('');select.value=state.models.some(model=>model.id===previous)?previous:'qwen2.5-1.5b';updateModelStatus()}
function updateModelStatus({fetchRuntime=true}={}){const model=state.models.find(item=>item.id===$('#model-select').value);if(!model)return;$('#model-detail').textContent=model.detail;$('#model-dot').classList.toggle('online',model.available);if($('#active-model-name'))$('#active-model-name').textContent=model.name;const label=model.ready?'Model ready':model.loading?'Loading model':model.available?'Ready to load':'Model offline',color=model.loading?'var(--amber)':model.available?'var(--green)':'var(--red)';$('#runtime-status').innerHTML=`<i style="background:${color}"></i>${label}`;if(!state.busy)$('#send-button').disabled=!model.available;if(fetchRuntime&&!state.busy&&model.id!=='evidence-guard'){const request=++state.runtimeRequest;fetchJSON(`/api/runtime?model=${encodeURIComponent(model.id)}`).then(runtime=>{if(request!==state.runtimeRequest||state.busy||$('#model-select').value!==model.id)return;state.runtime=runtime;model.ready=Boolean(runtime.ready);model.loading=Boolean(runtime.loading);renderRuntime(runtime,state.lastInference[model.id]);updateModelStatus({fetchRuntime:false})}).catch(()=>{})}}
function updateSessionCaption(){if($('#session-caption'))$('#session-caption').textContent=state.history.length?`${state.history.length} messages`:'New session'}
function applyResponseRuntime(data,modelId){state.runtimeRequest++;if(data.runtime){state.runtime=data.runtime;const model=state.models.find(item=>item.id===modelId);if(model){model.ready=Boolean(data.runtime.ready);model.loading=Boolean(data.runtime.loading);model.available=Boolean(data.runtime.installed||data.runtime.ready);const option=[...$('#model-select').options].find(item=>item.value===modelId);if(option)option.textContent=`${model.name} · ${model.ready?'ready':model.loading?'loading':'installed'}`}const last=`${data.usage?.total_tokens||0} tokens · ${Math.round(data.generation_ms)} ms`;state.lastInference[modelId]=last;renderRuntime(data.runtime,last)}updateModelStatus({fetchRuntime:false})}
function renderRuntime(runtime,last=null){if(!runtime)return;$('#runtime-engine').textContent=`${runtime.engine||'llama.cpp'} · ${runtime.device||'CPU'}`;$('#runtime-model').textContent=`${runtime.parameters||'—'} · ${runtime.quantization||'—'}`;if(last)$('#runtime-last').textContent=last;else $('#runtime-last').textContent=runtime.ready?`Endpoint ${new URL(runtime.endpoint).port} · ready`:runtime.installed?'Loads on first message':'Model not installed'}
function updateGuardLabel(){const enabled=$('#guardrail').checked;$('#active-mode').textContent=enabled?'Guardrail on':'Monitor only';$('#risk-threshold').disabled=!enabled}
function updateSearchLabel(){const enabled=$('#web-search').checked;$('#max-sources').disabled=!enabled;$('#max-sources-label').textContent=$('#max-sources').value}
function syncDrawerAccessibility(){const mobile=window.innerWidth<=980;let drawerOpen=false;['settings-panel','analysis-panel'].forEach(id=>{const panel=$(`#${id}`),open=panel.classList.contains('mobile-open');panel.inert=mobile&&!open;drawerOpen=drawerOpen||open});$('.workspace').inert=mobile&&drawerOpen}
function closeMobilePanels({restoreFocus=true}={}){const wasOpen=Boolean(document.querySelector('.mobile-open'));['settings-panel','analysis-panel'].forEach(id=>$(`#${id}`).classList.remove('mobile-open'));$('#mobile-backdrop').hidden=true;$('#open-settings').setAttribute('aria-expanded','false');$('#open-analysis').setAttribute('aria-expanded','false');syncDrawerAccessibility();if(wasOpen&&restoreFocus&&state.drawerTrigger?.isConnected&&state.drawerTrigger.getClientRects().length)state.drawerTrigger.focus({preventScroll:true});state.drawerTrigger=null}
function openMobilePanel(id){const panel=$(`#${id}`),wasOpen=panel.classList.contains('mobile-open');if(wasOpen){closeMobilePanels();return}closeMobilePanels({restoreFocus:false});state.drawerTrigger=$(id==='settings-panel'?'#open-settings':'#open-analysis');panel.classList.add('mobile-open');$('#mobile-backdrop').hidden=false;state.drawerTrigger.setAttribute('aria-expanded','true');syncDrawerAccessibility();panel.querySelector('.drawer-close')?.focus({preventScroll:true})}

function addMessage(role,text,meta=''){ $('#welcome')?.remove();const article=document.createElement('article');article.className=`message ${role}`;article.innerHTML=`<div class="avatar">${role==='user'?'YOU':'G'}</div><div><div class="bubble"></div>${meta?`<div class="message-meta">${meta}</div>`:''}</div>`;article.querySelector('.bubble').textContent=text;$('#conversation').appendChild(article);scrollConversation();return article}
function scrollConversation(){const el=$('#conversation');el.scrollTop=el.scrollHeight}
function setPipeline(label,detail=''){$('#pipeline-status').hidden=false;$('#pipeline-label').textContent=label;$('#pipeline-detail').textContent=detail}
function hidePipeline(){$('#pipeline-status').hidden=true}
function setBusy(busy){state.busy=busy;document.body.classList.toggle('is-generating',busy);$('#model-select').disabled=busy;$('#send-button').disabled=busy;$('#stop-button').hidden=!busy;$('#send-button').hidden=busy;if(!busy){hidePipeline();updateModelStatus({fetchRuntime:false})}}

async function submitQuestion(){
  if(state.busy)return;const question=$('#question-input').value.trim(),context=$('#context-input').value.trim();if(!question){$('#question-input').focus();return}
  const searching=$('#web-search').checked,modelId=$('#model-select').value,requestId=++state.requestId;state.runtimeRequest++;state.activeArticle=null;addMessage('user',question,searching?'Live search enabled':`${context.length.toLocaleString()} private-context characters`);$('#question-input').value='';autoGrow($('#question-input'));setBusy(true);state.stopped=false;state.abortController=new AbortController();
  resetAnalysis(searching?'Searching for relevant sources…':'Sending evidence to the local model…');setPipeline(searching?'Searching sources':'Preparing model',searching?'Retrieving attributable passages':'Using private evidence only');$('#analysis-state').className='analysis-state running';$('#analysis-state').textContent='SEARCHING';
  try{
    const data=await fetchJSON('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:state.abortController.signal,body:JSON.stringify({model:modelId,context,question,history:state.history.slice(-6),threshold:Number($('#risk-threshold').value),guardrail:$('#guardrail').checked,search_enabled:searching,max_sources:Number($('#max-sources').value)})});
    if(requestId!==state.requestId)return;
    state.history.push({role:'user',content:question},{role:'assistant',content:data.answer});updateSessionCaption();
    applyResponseRuntime(data,modelId);
    setPipeline(data.mode==='conversation'?'Conversation':'Auditing answer',data.mode==='conversation'?`${data.routing.method} · search skipped`:`${data.sources.length} sources · local generation ${Math.round(data.generation_ms)} ms`);renderSources(data.sources,data.search_skipped,data.search_error,data.search_query,data.original_search_query,data.analysis.source_reviews);await renderAnswer(data);
  }catch(error){if(requestId!==state.requestId)return;if(error.name==='AbortError'){addMessage('assistant','Generation stopped by you.','Request cancelled');$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='STOPPED';$('#action-value').textContent='Manual stop'}else{const detail=error.payload?.detail||'Check the local model runtime and network, then try again.';addMessage('assistant',`${error.message}\n\n${detail}`,'Request failed');updateAnalysisError(error.message)}setBusy(false)}finally{if(requestId===state.requestId)state.abortController=null}
}

function renderAnswer(data){return new Promise(resolve=>{const article=addMessage('assistant',''),bubble=article.querySelector('.bubble');state.activeArticle=article;state.streamResolve=resolve;bubble.classList.add('typing-cursor');const words=data.answer.split(/(\s+)/);let index=0;updateAnalysis(data,true);state.streamTimer=setInterval(()=>{if(state.stopped||index>=words.length){clearInterval(state.streamTimer);state.streamTimer=null;state.streamResolve=null;bubble.classList.remove('typing-cursor');if(!state.stopped){const partial=data.guardrail_triggered&&data.analysis.safe_claims_shown>0,label=data.mode==='conversation'?`${escapeHtml(data.model.name)} · chat · ${data.usage?.total_tokens||0} tokens`:partial?`Claims filtered · ${data.analysis.safe_claims_shown} strong match${data.analysis.safe_claims_shown===1?'':'es'} shown`:data.guardrail_triggered?'Guardrail hid the generated answer':`${Math.round(data.analysis.support*100)}% source match · ${data.usage?.total_tokens||0} tokens`;article.lastElementChild.insertAdjacentHTML('beforeend',`<div class="message-meta ${data.guardrail_triggered?'danger':'safe'}">${label} · ${Math.round(data.latency_ms)} ms${data.mode==='conversation'?'':` · ${data.sources.length} sources`}</div>`);updateAnalysis(data,false)}setBusy(false);scrollConversation();resolve();return}bubble.textContent+=words[index++];scrollConversation()},18)})}
function stopGeneration(){if(!state.busy)return;state.stopped=true;state.requestId++;state.abortController?.abort();state.abortController=null;if(state.streamTimer){clearInterval(state.streamTimer);state.streamTimer=null}const bubble=state.activeArticle?.querySelector('.bubble');if(bubble){bubble.classList.remove('typing-cursor');bubble.textContent+=(bubble.textContent?'\n\n':'')+'[Display stopped by user]'}else addMessage('assistant','Request cancelled.','Stopped by you');state.streamResolve?.();state.streamResolve=null;setBusy(false);$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='STOPPED';$('#action-value').textContent='Manual stop';scrollConversation()}

function resetAnalysis(message='Metrics appear here after a search and generation.'){updateRiskGauge(0,'idle');$('#analysis-state').className='analysis-state idle';$('#analysis-state').textContent='IDLE';$('#risk-value').textContent='—';$('#risk-title').textContent='Waiting for an answer';$('#risk-description').textContent=message;['support-value','latency-value','unsupported-value','action-value'].forEach(id=>$(`#${id}`).textContent='—');$('#sentence-total').textContent='0 sentences';$('#sentence-list').className='empty-evidence';$('#sentence-list').textContent='The generated answer will be audited sentence by sentence.';renderSources([])}
function updateRiskGauge(risk,mode){const color=risk>=.5?'var(--red)':risk>=.3?'var(--amber)':'var(--green)';$('#risk-ring').style.setProperty('--risk',Math.round(risk*100));$('#risk-ring').style.setProperty('--risk-color',color);if(mode!=='idle')$('#risk-value').textContent=percent(risk)}
function updateAnalysis(data,streaming){const analysis=data.analysis,casual=data.mode==='conversation',missing=!casual&&!analysis.evidence_available,risky=analysis.decision==='high-risk'||analysis.decision==='stopped',partial=data.guardrail_triggered&&analysis.safe_claims_shown>0;updateRiskGauge(analysis.risk,streaming?'running':risky?'risky':'safe');if(casual||missing)$('#risk-value').textContent='N/A';$('#risk-title').textContent=casual?'No factual claims to audit':missing?'No evidence to review':partial?'Partial answer · claims filtered':data.guardrail_triggered?'Generated answer hidden':risky?'Weak source match':'Claims match source text';$('#risk-description').textContent=casual?'Search and evidence checking were skipped for this conversation.':missing?'No retrieved or private source was available. This is unverified, not proof of hallucination.':partial?`${analysis.safe_claims_shown} claim${analysis.safe_claims_shown===1?' has':'s have'} a strong source-text match and remain visible. Other claims were hidden for review.`:data.guardrail_triggered?'The answer was hidden because its claims did not match an individual passage strongly enough.':'This is a passage-overlap estimate, not a factuality guarantee or the offline research probe.';$('#support-value').textContent=casual||missing?'N/A':percent(analysis.support);$('#latency-value').textContent=`${Math.round(data.latency_ms)} ms`;$('#unsupported-value').textContent=analysis.unsupported_count;$('#action-value').textContent=casual?'Not needed':missing?'No evidence':partial?'Filtered':data.guardrail_triggered?'Hidden':$('#guardrail').checked?'Allowed':'Observed';$('#analysis-state').className=`analysis-state ${streaming?'running':risky||missing?'risky':'safe'}`;$('#analysis-state').textContent=streaming?(casual?'CHATTING':'REVIEWING'):casual?'CHAT':missing?'UNVERIFIED':partial?'PARTIAL':data.guardrail_triggered?'HIDDEN':risky?'REVIEW':'MATCHED';renderSentenceEvidence(analysis.sentences)}
function renderSentenceEvidence(sentences){$('#sentence-total').textContent=`${sentences.length} sentence${sentences.length===1?'':'s'}`;$('#sentence-list').className='';$('#sentence-list').innerHTML=sentences.map(item=>{const sourceLabel=item.source_index?`[${item.source_index}] ${escapeHtml(item.source_title)}`:'';const sourceLink=item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noopener">${sourceLabel}</a>`:sourceLabel;const evidence=item.evidence_excerpt?`<div class="evidence-match"><strong>Reviewed passage · ${sourceLink}</strong><p>${escapeHtml(item.evidence_excerpt)}</p></div>`:item.status==='neutral'?'':'<div class="evidence-match">No matching source passage found.</div>';const label={supported:'strong text match',uncertain:'partial text match',unsupported:'no text match',neutral:'not audited'}[item.status]||item.status;return `<article class="sentence-item ${item.status}"><p>${escapeHtml(item.sentence)}</p><div class="sentence-score"><span>${label}</span><b>${item.support==null?'No factual claim':`${percent(item.support)} text match`}</b></div>${evidence}</article>`}).join('')}
function renderSources(sources,skipped=false,error=null,query='',originalQuery='',reviews=[]){$('#source-total').textContent=`${sources.length} source${sources.length===1?'':'s'}`;const analysisLabel=$('#open-analysis [data-analysis-label]')||$('#open-analysis');analysisLabel.textContent=sources.length?`Sources ${sources.length}`:'Analysis';const list=$('#source-list');if(!sources.length){list.className='empty-evidence';list.textContent=skipped?'Search skipped for conversational chat.':error?`Search failed: ${error}. Check your internet connection and try again.`:query?`No sources found for “${query}”. Try correcting the name or using different search terms.`:'Sources used by the model will appear here.';return}list.className='';const corrected=originalQuery&&query&&originalQuery.toLowerCase()!==query.toLowerCase()?`<p class="source-query">Showing results for “${escapeHtml(query)}” (original search: “${escapeHtml(originalQuery)}”)</p>`:'';const planned=query.includes(' | ')?`<p class="source-query">Searched separately: ${escapeHtml(query.replaceAll(' | ', ' and '))}</p>`:'';list.innerHTML=corrected+planned+sources.map((source,index)=>{const review=reviews?.[index],match=review?.strong_matches||0,topic=source.search_topic?` · ${escapeHtml(source.search_topic)}`:'';return `<a class="source-card" href="${escapeHtml(source.url)}" target="_blank" rel="noopener"><b>[${index+1}] ${escapeHtml(source.title)}</b><small>${match?`${match} claim${match===1?'':'s'} matched`:'Reviewed · no strong claim match'}${topic}</small><span>${escapeHtml(source.snippet.slice(0,180))}…</span></a>`}).join('')}
function updateAnalysisError(message){updateRiskGauge(1,'risky');$('#risk-value').textContent='—';$('#risk-title').textContent='Request could not run';$('#risk-description').textContent=message;$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='ERROR';$('#action-value').textContent='Blocked'}

function clearConversation(){closeMobilePanels();state.requestId++;state.abortController?.abort();state.abortController=null;if(state.streamTimer)clearInterval(state.streamTimer);state.streamTimer=null;state.streamResolve?.();state.streamResolve=null;state.activeArticle=null;state.stopped=true;state.busy=false;state.history=[];$('#conversation').innerHTML=welcomeMarkup;bindStarterButtons();updateSessionCaption();setBusy(false);resetAnalysis();$('#question-input').focus()}
const examples={search:{context:'',question:'How does retrieval-augmented generation reduce hallucinations in language models?'},research:{context:'This project records entropy, token probabilities, attention statistics, and hidden-state features. The full logistic probe achieved test AUROC 0.7154 and F1 0.6552 on 115 held-out examples.',question:'What signals and measured results does this hallucination project report?'},compare:{context:'',question:'Compare Marie Curie and Ada Lovelace and explain their main contributions.'}};
function bindStarterButtons(){document.querySelectorAll('.starter').forEach(button=>button.addEventListener('click',()=>{const value=examples[button.dataset.example];$('#context-input').value=value.context;$('#question-input').value=value.question;updateContextCount();$('#question-input').focus()}))}
function autoGrow(element){element.style.height='auto';element.style.height=`${Math.min(element.scrollHeight,130)}px`}
function updateContextCount(){$('#context-count').textContent=`${$('#context-input').value.length.toLocaleString()} characters`}
function renderResearch(results){const labels={entropy:'Entropy baseline',logistic:'Full logistic',mlp:'MLP probe'};$('#research-cards').innerHTML=Object.entries(results).map(([key,value])=>`<article class="research-card"><h3>${labels[key]}</h3><strong>${Number(value.test.auroc).toFixed(3)}</strong><span>TEST AUROC · F1 ${Number(value.test.f1).toFixed(3)} · ${value.n_features} FEATURES</span></article>`).join('')}

$('#model-select').addEventListener('change',updateModelStatus);$('#guardrail').addEventListener('change',updateGuardLabel);$('#web-search').addEventListener('change',updateSearchLabel);$('#max-sources').addEventListener('input',updateSearchLabel);$('#risk-threshold').addEventListener('input',()=>{$('#risk-threshold-label').textContent=percent($('#risk-threshold').value)});$('#send-button').addEventListener('click',submitQuestion);$('#stop-button').addEventListener('click',stopGeneration);$('#question-input').addEventListener('input',event=>autoGrow(event.target));$('#question-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submitQuestion()}});$('#context-input').addEventListener('input',updateContextCount);$('#clear-chat').addEventListener('click',clearConversation);$('#new-chat').addEventListener('click',clearConversation);$('#show-research').addEventListener('click',()=>$('#research-dialog').showModal());bindStarterButtons();initialize().catch(error=>updateAnalysisError(error.message));
$('#open-settings').addEventListener('click',()=>openMobilePanel('settings-panel'));$('#open-analysis').addEventListener('click',()=>openMobilePanel('analysis-panel'));$('#close-settings').addEventListener('click',closeMobilePanels);$('#close-analysis').addEventListener('click',closeMobilePanels);$('#mobile-backdrop').addEventListener('click',closeMobilePanels);window.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]'))return;if(event.key==='Escape')closeMobilePanels();if(event.key==='Tab'){const panel=document.querySelector('.mobile-open');if(!panel)return;const focusable=[...panel.querySelectorAll('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(element=>element.getClientRects().length),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});window.addEventListener('resize',()=>{if(window.innerWidth>980){closeMobilePanels({restoreFocus:false});return}const focusedPanel=document.activeElement?.closest('#settings-panel, #analysis-panel');syncDrawerAccessibility();if(focusedPanel?.inert)$(focusedPanel.id==='settings-panel'?'#open-settings':'#open-analysis').focus({preventScroll:true})});syncDrawerAccessibility();
