const state={models:[],summary:null,runtime:null,history:[],historyRecords:[],analysisHistory:[],analysisById:{},activeAnalysisId:null,lastQuestion:'',streamTimer:null,streamResolve:null,activeArticle:null,abortController:null,compareAbort:null,stopped:false,busy:false,requestId:0,runtimeRequest:0,lastInference:{},drawerTrigger:null};
const $=selector=>document.querySelector(selector);
const welcomeMarkup=$('#welcome').outerHTML;
const escapeHtml=value=>{const node=document.createElement('div');node.textContent=value??'';return node.innerHTML};
const percent=value=>`${Math.round(Number(value)*100)}%`;
const COMPACT_BREAKPOINT=1280;

async function fetchJSON(url,options={}){const response=await fetch(url,options);const data=await response.json();if(!response.ok){const error=new Error(data.error||'Request failed');error.payload=data;throw error}return data}

async function initialize(){const [models,summary,runtime]=await Promise.all([fetchJSON('/api/models'),fetchJSON('/api/summary'),fetchJSON('/api/runtime')]);state.models=models;state.summary=summary;state.runtime=runtime;renderModels(false);renderCompareOptions();renderRuntime(runtime);renderResearch(summary.results,summary.probe_status,summary.result_provenance,summary.signal_count,summary.aligned_signal_count);updateGuardLabel();updateSearchLabel();restoreAnalysisHistory();updateSessionCaption();if(models.some(model=>model.loading))pollModelStatus()}
async function pollModelStatus(){for(let attempt=0;attempt<60;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));try{state.models=await fetchJSON('/api/models');renderModels(true);if(!state.models.some(model=>model.loading))break}catch{}}}
function renderModels(preserve=true){const select=$('#model-select'),previous=preserve?select.value:'';select.innerHTML=state.models.map(model=>{const suffix=model.ready?' · ready':model.loading?' · loading':model.available?' · installed':' · offline';return `<option value="${model.id}">${escapeHtml(model.name+suffix)}</option>`}).join('');select.value=state.models.some(model=>model.id===previous)?previous:'qwen2.5-1.5b';updateModelStatus()}
function updateModelStatus({fetchRuntime=true}={}){const model=state.models.find(item=>item.id===$('#model-select').value);if(!model)return;$('#model-detail').textContent=model.detail;$('#model-dot').classList.toggle('online',model.available);if($('#active-model-name'))$('#active-model-name').textContent=model.name;const label=model.ready?'Model ready':model.loading?'Loading model':model.available?'Ready to load':'Model offline',color=model.loading?'var(--amber)':model.available?'var(--green)':'var(--red)';$('#runtime-status').innerHTML=`<i style="background:${color}"></i>${label}`;if(!state.busy)$('#send-button').disabled=!model.available;if(fetchRuntime&&!state.busy&&model.id!=='evidence-guard'){const request=++state.runtimeRequest;fetchJSON(`/api/runtime?model=${encodeURIComponent(model.id)}`).then(runtime=>{if(request!==state.runtimeRequest||state.busy||$('#model-select').value!==model.id)return;state.runtime=runtime;model.ready=Boolean(runtime.ready);model.loading=Boolean(runtime.loading);renderRuntime(runtime,state.lastInference[model.id]);updateModelStatus({fetchRuntime:false})}).catch(()=>{})}}
function updateSessionCaption(){if($('#session-caption'))$('#session-caption').textContent=state.history.length?`${state.history.length} messages`:'New session'}
function applyResponseRuntime(data,modelId){state.runtimeRequest++;if(data.runtime){state.runtime=data.runtime;const model=state.models.find(item=>item.id===modelId);if(model){model.ready=Boolean(data.runtime.ready);model.loading=Boolean(data.runtime.loading);model.available=Boolean(data.runtime.installed||data.runtime.ready);const option=[...$('#model-select').options].find(item=>item.value===modelId);if(option)option.textContent=`${model.name} · ${model.ready?'ready':model.loading?'loading':'installed'}`}const last=`${data.usage?.total_tokens||0} tokens · ${Math.round(data.generation_ms)} ms`;state.lastInference[modelId]=last;renderRuntime(data.runtime,last)}updateModelStatus({fetchRuntime:false})}
function renderRuntime(runtime,last=null){if(!runtime)return;$('#runtime-engine').textContent=`${runtime.engine||'llama.cpp'} · ${runtime.device||'CPU'}`;$('#runtime-model').textContent=`${runtime.parameters||'—'} · ${runtime.quantization||'—'}`;if(last)$('#runtime-last').textContent=last;else $('#runtime-last').textContent=runtime.ready?`Endpoint ${new URL(runtime.endpoint).port} · ready`:runtime.installed?'Loads on first message':'Model not installed'}
function updateGuardLabel(){const enabled=$('#guardrail').checked;$('#active-mode').textContent=enabled?'Guardrail on':'Monitor only';$('#risk-threshold').disabled=!enabled}
function updateSearchLabel(){const enabled=$('#web-search').checked;$('#max-sources').disabled=!enabled;$('#max-sources-label').textContent=$('#max-sources').value}
function syncDrawerAccessibility(){const mobile=window.innerWidth<=COMPACT_BREAKPOINT;let drawerOpen=false;['settings-panel','analysis-panel'].forEach(id=>{const panel=$(`#${id}`),open=panel.classList.contains('mobile-open');panel.inert=mobile&&!open;drawerOpen=drawerOpen||open});$('.workspace').inert=mobile&&drawerOpen}
function closeMobilePanels({restoreFocus=true}={}){const wasOpen=Boolean(document.querySelector('.mobile-open'));['settings-panel','analysis-panel'].forEach(id=>$(`#${id}`).classList.remove('mobile-open'));$('#mobile-backdrop').hidden=true;$('#open-settings').setAttribute('aria-expanded','false');$('#open-analysis').setAttribute('aria-expanded','false');syncDrawerAccessibility();if(wasOpen&&restoreFocus&&state.drawerTrigger?.isConnected&&state.drawerTrigger.getClientRects().length)state.drawerTrigger.focus({preventScroll:true});state.drawerTrigger=null}
function openMobilePanel(id){const panel=$(`#${id}`),wasOpen=panel.classList.contains('mobile-open');if(wasOpen){closeMobilePanels();return}closeMobilePanels({restoreFocus:false});state.drawerTrigger=$(id==='settings-panel'?'#open-settings':'#open-analysis');panel.classList.add('mobile-open');$('#mobile-backdrop').hidden=false;state.drawerTrigger.setAttribute('aria-expanded','true');syncDrawerAccessibility();panel.querySelector('.drawer-close')?.focus({preventScroll:true})}

function addMessage(role,text,meta=''){ $('#welcome')?.remove();const article=document.createElement('article');article.className=`message ${role}`;article.innerHTML=`<div class="avatar">${role==='user'?'YOU':'G'}</div><div><div class="bubble"></div>${meta?`<div class="message-meta">${meta}</div>`:''}</div>`;article.querySelector('.bubble').textContent=text;$('#conversation').appendChild(article);scrollConversation();return article}
function analysisId(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function saveAnalysisHistory(){try{localStorage.setItem('grounded-analysis-history-v1',JSON.stringify(state.analysisHistory.slice(-30)))}catch(error){console.warn('Analysis history could not be saved',error)}}
function registerAnalysis(question,data,article,{persist=true}={}){const record={id:analysisId(),timestamp:new Date().toISOString(),question,data};state.analysisHistory.push(record);state.analysisById[record.id]=record;if(persist)saveAnalysisHistory();attachAnalysisButton(article,record.id);return record}
function attachAnalysisButton(article,id){article.dataset.analysisId=id;let button=article.querySelector('.analysis-button');if(!button){button=document.createElement('button');button.type='button';button.className='analysis-button';button.textContent='View analysis';button.addEventListener('click',()=>viewAnalysis(id,true));article.lastElementChild.appendChild(button)}}
function restoreAnalysisHistory(){let saved=[];try{saved=JSON.parse(localStorage.getItem('grounded-analysis-history-v1')||'[]')}catch{}if(!Array.isArray(saved)||!saved.length)return;state.analysisHistory=saved.slice(-30);state.analysisById=Object.fromEntries(state.analysisHistory.map(row=>[row.id,row]));$('#conversation').innerHTML='';state.history=[];for(const record of state.analysisHistory){addMessage('user',record.question,'Restored local session');const article=addMessage('assistant',record.data.answer,`${record.data.model?.name||record.data.model?.id||'Local model'} · saved ${new Date(record.timestamp).toLocaleString()}`);attachAnalysisButton(article,record.id);state.history.push({role:'user',content:record.question},{role:'assistant',content:record.data.answer})}viewAnalysis(state.analysisHistory.at(-1).id,false)}
function viewAnalysis(id,openPanel=false){const record=state.analysisById[id];if(!record)return;state.activeAnalysisId=id;document.querySelectorAll('.message').forEach(item=>item.classList.toggle('analysis-selected',item.dataset.analysisId===id));$('#analysis-selection').textContent=`${record.question} · ${new Date(record.timestamp).toLocaleTimeString()}`;const data=record.data;renderSources(data.sources||[],data.search_skipped,data.search_error,data.search_query,data.original_search_query,data.analysis?.source_reviews,data.retrieval);updateAnalysis(data,false);if(data.verifier)$('.review-caveat').textContent=data.verifier.loaded?'Local NLI evidence review. Scores are uncalibrated; supporting evidence is not proof of truth.':'Lexical fallback active. Semantic verifier unavailable.';const panel=$('#analysis-panel');if(openPanel&&window.innerWidth<=COMPACT_BREAKPOINT&&!panel.classList.contains('mobile-open'))openMobilePanel('analysis-panel');panel.scrollTop=0}
function scrollConversation(){const el=$('#conversation');el.scrollTop=el.scrollHeight}
function setPipeline(label,detail=''){$('#pipeline-status').hidden=false;$('#pipeline-label').textContent=label;$('#pipeline-detail').textContent=detail}
function hidePipeline(){$('#pipeline-status').hidden=true}
function setBusy(busy){state.busy=busy;document.body.classList.toggle('is-generating',busy);$('#model-select').disabled=busy;$('#send-button').disabled=busy;$('#stop-button').hidden=!busy;$('#send-button').hidden=busy;if(!busy){hidePipeline();updateModelStatus({fetchRuntime:false})}}

async function submitQuestion(){
  if(state.busy)return;const question=$('#question-input').value.trim(),context=$('#context-input').value.trim();if(!question){$('#question-input').focus();return}state.lastQuestion=question;
  const searching=$('#web-search').checked,modelId=$('#model-select').value,requestId=++state.requestId;state.runtimeRequest++;state.activeArticle=null;addMessage('user',question,searching?'Live search enabled':`${context.length.toLocaleString()} private-context characters`);$('#question-input').value='';autoGrow($('#question-input'));setBusy(true);state.stopped=false;state.abortController=new AbortController();
  resetAnalysis(searching?'Searching for relevant sources…':'Sending evidence to the local model…');setPipeline(searching?'Searching sources':'Preparing model',searching?'Retrieving attributable passages':'Using private evidence only');$('#analysis-state').className='analysis-state running';$('#analysis-state').textContent='SEARCHING';
  try{
    const data=await streamChat({model:modelId,context,question,history:state.history.slice(-6),threshold:Number($('#risk-threshold').value),guardrail:$('#guardrail').checked,search_enabled:searching,max_sources:Number($('#max-sources').value)},state.abortController.signal,event=>renderLiveEvent(event,requestId));
    if(requestId!==state.requestId)return;
    state.history.push({role:'user',content:question},{role:'assistant',content:data.answer});updateSessionCaption();
    applyResponseRuntime(data,modelId);
    setPipeline(data.mode==='conversation'?'Conversation':'Auditing answer',data.mode==='conversation'?`${data.routing.method} · search skipped`:`${data.sources.length} sources · local generation ${Math.round(data.generation_ms)} ms`);renderSources(data.sources,data.search_skipped,data.search_error,data.search_query,data.original_search_query,data.analysis.source_reviews,data.retrieval);await renderAnswer(data);
  }catch(error){if(requestId!==state.requestId)return;if(error.name==='AbortError'){addMessage('assistant','Generation stopped by you.','Request cancelled');$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='STOPPED';$('#action-value').textContent='Manual stop'}else{const detail=error.payload?.detail||'Check the local model runtime and network, then try again.';addMessage('assistant',`${error.message}\n\n${detail}`,'Request failed');updateAnalysisError(error.message)}setBusy(false)}finally{if(requestId===state.requestId)state.abortController=null}
}

function renderAnswer(data){const article=state.activeArticle||addMessage('assistant','');article.querySelector('.bubble').textContent=data.answer;article.lastElementChild.insertAdjacentHTML('beforeend',`<div class="message-meta">${escapeHtml(data.model.name)} · ${Math.round(data.latency_ms)} ms · ${data.sources.length} sources</div>`);if(data.research_probe){const note=document.createElement('p');note.className='message-meta';note.textContent=`Experimental internal-probe score: ${data.research_probe.raw_score.toFixed(3)} · ${data.research_probe.features} real features. Unvalidated legacy score, not a hallucination probability; not used for blocking.`;article.lastElementChild.appendChild(note)}const record=registerAnalysis(state.lastQuestion,data,article);state.activeArticle=null;viewAnalysis(record.id,false);setBusy(false);scrollConversation();return Promise.resolve()}
async function streamChat(payload,signal,onEvent=()=>{}){
  const created=await fetchJSON('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const cancel=()=>fetchJSON(`/api/jobs/${created.id}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});
  signal?.addEventListener('abort',cancel,{once:true});
  let cursor=0,result;
  try{
    if(signal?.aborted){await cancel();throw new DOMException('Cancelled','AbortError')}
    while(true){
      const snapshot=await fetchJSON(`/api/jobs/${created.id}?cursor=${cursor}`,{signal});
      cursor=snapshot.cursor;
      for(const event of snapshot.events){
        if(event.type==='error'){const error=new Error(event.data?.error||'Request failed');error.payload=event.data;throw error}
        if(event.type==='result')result=event.data;
        onEvent(event);
      }
      if(snapshot.done){if(snapshot.cancelled)throw new DOMException('Cancelled','AbortError');if(!result)throw new Error('Generation ended without a result');return result}
      await new Promise(resolve=>setTimeout(resolve,180));
    }
  }finally{signal?.removeEventListener('abort',cancel)}
}
function renderLiveEvent(event,requestId){
  if(requestId!==state.requestId)return;
  if(event.type==='sources'){renderSources(event.sources,false,event.search_error);setPipeline('Generating and checking claims',event.resolved_question)}
  if(event.type==='progress'){setPipeline(event.stage==='loading-research-model'?'Loading experimental research model':'Model is generating','Completed sentences are checked before display')}
  if(event.type==='token'||event.type==='claim'){
    state.activeArticle=state.activeArticle||addMessage('assistant','');
    const bubble=state.activeArticle.querySelector('.bubble');
    if(event.type==='token')bubble.textContent+=event.text;
    else{
      if(!event.claim.blocked)bubble.textContent+=(bubble.textContent?'\n':'')+event.claim.sentence;
      setPipeline(event.claim.blocked?'Guard stopped inference':'Claim reviewed',event.claim.reason);
    }
    scrollConversation();
  }
}
function stopGeneration(){if(!state.busy)return;state.stopped=true;state.requestId++;state.abortController?.abort();state.abortController=null;if(state.streamTimer){clearInterval(state.streamTimer);state.streamTimer=null}const bubble=state.activeArticle?.querySelector('.bubble');if(bubble){bubble.classList.remove('typing-cursor');bubble.textContent+=(bubble.textContent?'\n\n':'')+'[Display stopped by user]'}else addMessage('assistant','Request cancelled.','Stopped by you');state.streamResolve?.();state.streamResolve=null;setBusy(false);$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='STOPPED';$('#action-value').textContent='Manual stop';scrollConversation()}

function resetAnalysis(message='Metrics appear here after a search and generation.'){updateRiskGauge(0,'idle');$('#analysis-state').className='analysis-state idle';$('#analysis-state').textContent='IDLE';$('#risk-value').textContent='—';$('#risk-title').textContent='Waiting for an answer';$('#risk-description').textContent=message;['support-value','latency-value','unsupported-value','action-value'].forEach(id=>$(`#${id}`).textContent='—');$('#sentence-total').textContent='0 sentences';$('#sentence-list').className='empty-evidence';$('#sentence-list').textContent='The generated answer will be audited sentence by sentence.';renderSources([])}
function updateRiskGauge(risk,mode){const color=risk>=.5?'var(--red)':risk>=.3?'var(--amber)':'var(--green)';$('#risk-ring').style.setProperty('--risk',Math.round(risk*100));$('#risk-ring').style.setProperty('--risk-color',color);if(mode!=='idle')$('#risk-value').textContent=percent(risk)}
function updateAnalysis(data,streaming){const analysis=data.analysis,casual=data.mode==='conversation',missing=!casual&&!analysis.evidence_available,risky=analysis.decision==='high-risk'||analysis.decision==='stopped',partial=data.guardrail_triggered&&analysis.safe_claims_shown>0,counts=analysis.status_counts||{};updateRiskGauge(analysis.weakest_claim_risk??analysis.risk,streaming?'running':risky?'risky':'safe');if(casual||missing)$('#risk-value').textContent='N/A';$('#risk-title').textContent=casual?'No factual claims to audit':missing?'No evidence to review':partial?'Partial answer · claims filtered':data.guardrail_triggered?'Generated answer hidden':risky?'A claim needs review':'Claims match reviewed evidence';$('#risk-description').textContent=casual?'Search and evidence checking were skipped for this conversation.':analysis.guard_reason||'This is evidence verification, not a probability that the whole answer is false.';$('#support-value').textContent=casual||missing?'N/A':percent(analysis.evidence_coverage??analysis.support);$('#latency-value').textContent=`${Math.round(data.latency_ms)} ms`;$('#unsupported-value').textContent=casual?'—':`${(counts.contradicted||0)+(counts.unverified||0)}`;$('#action-value').textContent=casual?'Not needed':missing?'No evidence':partial?'Filtered':data.guardrail_triggered?'Hidden':$('#guardrail').checked?'Allowed':'Observed';$('#analysis-state').className=`analysis-state ${streaming?'running':risky||missing?'risky':'safe'}`;$('#analysis-state').textContent=streaming?(casual?'CHATTING':'REVIEWING'):casual?'CHAT':missing?'UNVERIFIED':partial?'PARTIAL':data.guardrail_triggered?'HIDDEN':risky?'REVIEW':'MATCHED';renderSentenceEvidence(analysis.sentences)}
function renderSentenceEvidence(sentences){$('#sentence-total').textContent=`${sentences.length} claim${sentences.length===1?'':'s'}`;$('#sentence-list').className='';$('#sentence-list').innerHTML=sentences.map(item=>{const sourceLabel=item.source_index?`[${item.source_index}] ${escapeHtml(item.source_title)}`:'';const sourceLink=item.source_url?`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noopener">${sourceLabel}</a>`:sourceLabel;const reason=item.reason?`<small>${escapeHtml(item.reason)}</small>`:'';const evidence=item.evidence_excerpt?`<div class="evidence-match"><strong>Reviewed passage · ${sourceLink}</strong><p>${escapeHtml(item.evidence_excerpt)}</p>${reason}</div>`:item.status==='neutral'?'':`<div class="evidence-match">No matching source passage found.${reason}</div>`;const label={supported:'supported',partial:'partial support',contradicted:'contradicted',unverified:'unverified',neutral:'not audited'}[item.status]||item.status;return `<article class="sentence-item ${item.status}"><p>${escapeHtml(item.sentence)}</p><div class="sentence-score"><span>${label}</span><b>${item.support==null?'No factual claim':`${percent(item.support)} evidence match`}</b></div>${evidence}</article>`}).join('')}
function renderSources(sources,skipped=false,error=null,query='',originalQuery='',reviews=[],retrieval=null){$('#source-total').textContent=`${sources.length} source${sources.length===1?'':'s'}`;const analysisLabel=$('#open-analysis [data-analysis-label]')||$('#open-analysis');analysisLabel.textContent=sources.length?`Sources ${sources.length}`:'Analysis';const list=$('#source-list');if(!sources.length){list.className='empty-evidence';list.textContent=skipped?'Search skipped for conversational chat.':error?`Search failed after automatic retries: ${error}. Check your internet connection and try again.`:query?`No sources found for “${query}”. Try correcting the name or using different search terms.`:'Sources used by the model will appear here.';return}list.className='';const attempts=retrieval?.attempts||[],cached=attempts.some(item=>item.cached),attemptCount=attempts.reduce((sum,item)=>sum+(item.attempts||0),0);const health=`<p class="source-query">Wikipedia retrieval · ${cached?'cache hit':`${attemptCount} network attempt${attemptCount===1?'':'s'}`} · ranked passages</p>`;const corrected=originalQuery&&query&&originalQuery.toLowerCase()!==query.toLowerCase()?`<p class="source-query">Showing results for “${escapeHtml(query)}” (original search: “${escapeHtml(originalQuery)}”)</p>`:'';const planned=query.includes(' | ')?`<p class="source-query">Searched separately: ${escapeHtml(query.replaceAll(' | ', ' and '))}</p>`:'';list.innerHTML=health+corrected+planned+sources.map((source,index)=>{const review=reviews?.[index],match=review?.strong_matches||0,topic=source.search_topic?` · ${escapeHtml(source.search_topic)}`:'',score=source.retrieval_score==null?'':` · relevance ${Math.round(source.retrieval_score*100)}%`;return `<a class="source-card" href="${escapeHtml(source.url)}" target="_blank" rel="noopener"><b>[${index+1}] ${escapeHtml(source.title)}</b><small>${match?`${match} claim${match===1?'':'s'} matched`:'Reviewed · no strong claim match'}${topic}${score}</small><span>${escapeHtml(source.snippet.slice(0,180))}…</span></a>`}).join('')}
function updateAnalysisError(message){updateRiskGauge(1,'risky');$('#risk-value').textContent='—';$('#risk-title').textContent='Request could not run';$('#risk-description').textContent=message;$('#analysis-state').className='analysis-state risky';$('#analysis-state').textContent='ERROR';$('#action-value').textContent='Blocked'}

function clearConversation(){closeMobilePanels();state.requestId++;state.abortController?.abort();state.abortController=null;if(state.streamTimer)clearInterval(state.streamTimer);state.streamTimer=null;state.streamResolve?.();state.streamResolve=null;state.activeArticle=null;state.stopped=true;state.busy=false;state.history=[];state.analysisHistory=[];state.analysisById={};state.activeAnalysisId=null;localStorage.removeItem('grounded-analysis-history-v1');$('#analysis-selection').textContent='No answer selected';$('#conversation').innerHTML=welcomeMarkup;bindStarterButtons();updateSessionCaption();setBusy(false);resetAnalysis();$('#question-input').focus()}
const examples={search:{context:'',question:'How does retrieval-augmented generation reduce hallucinations in language models?'},research:{context:'This project records entropy, token probabilities, attention statistics, and hidden-state features. The full logistic probe achieved test AUROC 0.7154 and F1 0.6552 on 115 held-out examples.',question:'What signals and measured results does this hallucination project report?'},compare:{context:'',question:'Compare Marie Curie and Ada Lovelace and explain their main contributions.'}};
function bindStarterButtons(){document.querySelectorAll('.starter').forEach(button=>button.addEventListener('click',()=>{const value=examples[button.dataset.example];$('#context-input').value=value.context;$('#question-input').value=value.question;updateContextCount();$('#question-input').focus()}))}
function autoGrow(element){element.style.height='auto';element.style.height=`${Math.min(element.scrollHeight,130)}px`}
function updateContextCount(){$('#context-count').textContent=`${$('#context-input').value.length.toLocaleString()} characters`}
function renderResearch(results,probeStatus,provenance='',signalCount=0,alignedSignalCount=0){const labels={entropy:'Entropy baseline',logistic:'Full logistic',mlp:'MLP probe'},aligned=provenance.startsWith('aligned');$('#research-cards').innerHTML=Object.entries(results).map(([key,value])=>`<article class="research-card"><h3>${labels[key]}</h3><strong>${Number(value.test.auroc).toFixed(3)}</strong><span>TEST AUROC · F1 ${Number(value.test.f1).toFixed(3)} · ${value.n_features} FEATURES</span><span class="metric-bar" role="img" aria-label="${labels[key]} AUROC ${Number(value.test.auroc).toFixed(3)}"><i style="width:${Number(value.test.auroc)*100}%"></i></span></article>`).join('');$('#probe-live-status').textContent=`Live internal-signal probability: ${probeStatus?.live_probability_available?'available':'unavailable'}. ${probeStatus?.reason||''}`;const logistic=results.logistic;$('#benchmark-status').textContent=aligned?'ALIGNED / HELD OUT':'LEGACY / UNVALIDATED';$('#benchmark-auroc').textContent=logistic?Number(logistic.test.auroc).toFixed(3):'—';$('#benchmark-f1').textContent=logistic?Number(logistic.test.f1).toFixed(3):'—';$('#benchmark-signals').textContent=String(signalCount||'—');$('#benchmark-note').textContent=aligned?'Exact annotated responses are paired with their labels. This remains a research classifier, not a factuality probability.':`Legacy labels do not match generated answers. Aligned extraction is running (${alignedSignalCount}/749); these scores are not validated hallucination accuracy.`;$('#research-provenance').textContent=aligned?'Active results use exact annotated-response alignment and a held-out test split. They do not by themselves establish calibrated live-chat accuracy, causal validity, cross-model transfer, or steering effectiveness.':`Legacy results are shown while aligned extraction runs (${alignedSignalCount}/749 signals currently available). The audit found that 748 of 749 legacy saved answers differed from the originally labelled answers, so these legacy scores are not detection accuracy claims.`}

function renderCompareOptions(){const models=state.models.filter(model=>model.id!=='evidence-guard'&&model.installed);$('#compare-model-options').innerHTML=models.map((model,index)=>`<label><input type="checkbox" value="${escapeHtml(model.id)}" ${index<2?'checked':''}>${escapeHtml(model.name)}</label>`).join('')}
function openComparison(){const question=$('#question-input').value.trim()||state.lastQuestion;$('#compare-question').value=question;$('#compare-dialog').showModal()}
function answerAgreement(results){if(results.length<2)return null;const sets=results.map(item=>new Set((item.data?.answer||'').toLowerCase().match(/[a-z0-9]+/g)||[]));let total=0,pairs=0;for(let i=0;i<sets.length;i++)for(let j=i+1;j<sets.length;j++){const union=new Set([...sets[i],...sets[j]]),intersection=[...sets[i]].filter(token=>sets[j].has(token));total+=intersection.length/Math.max(union.size,1);pairs++}return total/Math.max(pairs,1)}
async function runComparison(){
  if(state.compareAbort)return;
  const question=$('#compare-question').value.trim(),models=[...document.querySelectorAll('#compare-model-options input:checked')].map(input=>input.value);
  if(!question||models.length<2){$('#compare-status').textContent='Enter a question and choose at least two models.';return}
  const controller=new AbortController();state.compareAbort=controller;
  const settings={context:$('#context-input').value.trim(),threshold:Number($('#risk-threshold').value),guardrail:false,search_enabled:$('#web-search').checked,max_sources:Number($('#max-sources').value),temperature:.15,max_tokens:240,history:[]};
  $('#run-comparison').disabled=true;$('#cancel-comparison').hidden=false;$('#compare-results').innerHTML='';
  const results=[];
  try{
    $('#compare-status').textContent='Retrieving one shared evidence snapshot…';
    const snapshot=await fetchJSON('/api/evidence',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({...settings,question})});
    for(const model of models){
      if(controller.signal.aborted)break;
      const info=state.models.find(item=>item.id===model);
      $('#compare-status').textContent=`Running ${info.name} · evidence ${snapshot.snapshot_id}`;
      try{
        const data=await streamChat({...settings,model,question,evidence_snapshot:snapshot},controller.signal);
        results.push({model:info,data});
        const counts=data.analysis.status_counts||{};
        $('#compare-results').insertAdjacentHTML('beforeend',`<article class="compare-result"><h3>${escapeHtml(info.name)}</h3><p>${escapeHtml(data.answer)}</p><div class="compare-metrics"><span>Coverage<b>${percent(data.analysis.evidence_coverage)}</b></span><span>Review claims<b>${(counts.contradicted||0)+(counts.unverified||0)}</b></span><span>Inference<b>${Math.round(data.generation_ms)} ms</b></span><span>Evidence ID<b>${escapeHtml(data.snapshot_id)}</b></span></div></article>`);
      }catch(error){if(error.name==='AbortError')break;$('#compare-results').insertAdjacentHTML('beforeend',`<article class="compare-result"><h3>${escapeHtml(info.name)}</h3><p>${escapeHtml(error.message)}</p></article>`)}
    }
    const agreement=answerAgreement(results);
    $('#compare-status').textContent=controller.signal.aborted?`Cancelled · ${results.length} completed result(s) kept`:`Complete · wording overlap ${agreement==null?'N/A':percent(agreement)} (not factual agreement)`;
  }catch(error){$('#compare-status').textContent=error.name==='AbortError'?'Cancelled':error.message}
  finally{$('#run-comparison').disabled=false;$('#cancel-comparison').hidden=true;state.compareAbort=null}
}
function cancelComparison(){state.compareAbort?.abort()}
function filteredHistory(){const model=$('#history-model-filter').value,status=$('#history-status-filter').value;return state.historyRecords.filter(row=>(!model||row.model_id===model)&&(!status||row.decision===status))}
function renderHistory(){const rows=filteredHistory(),list=$('#history-list');list.innerHTML=rows.length?rows.map((row,index)=>`<article class="history-row"><span><b>${escapeHtml(row.model_id)}</b><br>${new Date(row.timestamp).toLocaleString()}</span><span>Coverage<br><b>${row.evidence_coverage==null?'N/A':percent(row.evidence_coverage)}</b></span><span>Weakest<br><b>${row.weakest_claim_risk==null?'N/A':percent(row.weakest_claim_risk)}</b></span><span>${escapeHtml(row.decision||row.mode)}<br>${row.timings_ms?.total?Math.round(row.timings_ms.total)+' ms':'—'}</span><span class="history-actions"><button type="button" data-view-history="${index}" ${row.analysis&&row.answer?'':'disabled'}>View</button><button type="button" data-history-index="${index}">JSON</button></span></article>`).join(''):'<div class="empty-evidence">No matching local experiments yet.</div>';list.querySelectorAll('[data-history-index]').forEach(button=>button.addEventListener('click',()=>downloadFile(`grounded-run-${rows[Number(button.dataset.historyIndex)].question_id}.json`,JSON.stringify(rows[Number(button.dataset.historyIndex)],null,2),'application/json')));list.querySelectorAll('[data-view-history]').forEach(button=>button.addEventListener('click',()=>viewStoredAnalysis(rows[Number(button.dataset.viewHistory)])))}
function viewStoredAnalysis(row){const data={answer:row.answer,analysis:row.analysis,sources:row.sources||[],retrieval:row.retrieval,search_error:row.search_error,search_skipped:row.mode==='conversation',latency_ms:row.timings_ms?.total||0,mode:row.mode,model:{name:row.model_id},guardrail_triggered:row.analysis?.decision==='stopped'};const record={id:`ledger-${row.run_id||row.question_id}`,timestamp:row.timestamp,question:row.question||`Question ${row.question_id}`,data};state.analysisById[record.id]=record;$('#history-dialog').close();viewAnalysis(record.id,true)}
async function openHistory(){state.historyRecords=await fetchJSON('/api/history?limit=500');const models=[...new Set(state.historyRecords.map(row=>row.model_id))],statuses=[...new Set(state.historyRecords.map(row=>row.decision).filter(Boolean))];$('#history-model-filter').innerHTML='<option value="">All models</option>'+models.map(value=>`<option>${escapeHtml(value)}</option>`).join('');$('#history-status-filter').innerHTML='<option value="">All decisions</option>'+statuses.map(value=>`<option>${escapeHtml(value)}</option>`).join('');renderHistory();$('#history-dialog').showModal()}
function downloadFile(name,content,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function exportHistory(format){const rows=filteredHistory();if(format==='json'){downloadFile('grounded-experiments.json',JSON.stringify(rows,null,2),'application/json');return}const columns=['timestamp','question_id','model_id','quantization','mode','decision','evidence_coverage','weakest_claim_risk','score_version'],escape=value=>`"${String(value??'').replaceAll('"','""')}"`;downloadFile('grounded-experiments.csv',[columns.join(','),...rows.map(row=>columns.map(key=>escape(row[key])).join(','))].join('\n'),'text/csv')}
async function importDocument(){const file=$('#document-input').files[0];if(!file)return;if(file.size>8*1024*1024){$('#document-status').textContent='File exceeds 8 MB';return}$('#document-status').textContent='Reading locally…';const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let start=0;start<bytes.length;start+=32768)binary+=String.fromCharCode(...bytes.subarray(start,start+32768));try{const data=await fetchJSON('/api/documents/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,content_base64:btoa(binary)})});$('#context-input').value=data.text;updateContextCount();$('#document-status').textContent=`${data.filename} · ${data.characters.toLocaleString()} characters`;$('#context-panel').open=true}catch(error){$('#document-status').textContent=error.message}}
const demos={supported:{context:'Paris is the capital and most populous city of France.',question:'What is the capital of France?'},contradicted:{context:'The Apollo 11 mission landed on the Moon in 1969.',question:'Using only my evidence, explain whether Apollo 11 landed in 1972.'},fabricated:{context:'Marie Curie researched radioactivity and won Nobel Prizes in Physics and Chemistry.',question:'Did Marie Curie invent the telephone in 1895?'}};
function loadDemo(name){const demo=demos[name];$('#context-input').value=demo.context;$('#question-input').value=demo.question;updateContextCount();$('#research-dialog').close();$('#context-panel').open=true;$('#question-input').focus()}

$('#model-select').addEventListener('change',updateModelStatus);$('#guardrail').addEventListener('change',updateGuardLabel);$('#web-search').addEventListener('change',updateSearchLabel);$('#max-sources').addEventListener('input',updateSearchLabel);$('#risk-threshold').addEventListener('input',()=>{$('#risk-threshold-label').textContent=percent($('#risk-threshold').value)});$('#send-button').addEventListener('click',submitQuestion);$('#stop-button').addEventListener('click',stopGeneration);$('#question-input').addEventListener('input',event=>autoGrow(event.target));$('#question-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submitQuestion()}});$('#context-input').addEventListener('input',updateContextCount);$('#clear-chat').addEventListener('click',clearConversation);$('#new-chat').addEventListener('click',clearConversation);$('#show-research').addEventListener('click',()=>$('#research-dialog').showModal());bindStarterButtons();initialize().catch(error=>updateAnalysisError(error.message));
$('#open-settings').addEventListener('click',()=>openMobilePanel('settings-panel'));$('#open-analysis').addEventListener('click',()=>openMobilePanel('analysis-panel'));$('#close-settings').addEventListener('click',closeMobilePanels);$('#close-analysis').addEventListener('click',closeMobilePanels);$('#mobile-backdrop').addEventListener('click',closeMobilePanels);window.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]'))return;if(event.key==='Escape')closeMobilePanels();if(event.key==='Tab'){const panel=document.querySelector('.mobile-open');if(!panel)return;const focusable=[...panel.querySelectorAll('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(element=>element.getClientRects().length),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});window.addEventListener('resize',()=>{if(window.innerWidth>COMPACT_BREAKPOINT){closeMobilePanels({restoreFocus:false});return}const focusedPanel=document.activeElement?.closest('#settings-panel, #analysis-panel');syncDrawerAccessibility();if(focusedPanel?.inert)$(focusedPanel.id==='settings-panel'?'#open-settings':'#open-analysis').focus({preventScroll:true})});syncDrawerAccessibility();
$('#compare-models').addEventListener('click',openComparison);$('#run-comparison').addEventListener('click',runComparison);$('#cancel-comparison').addEventListener('click',cancelComparison);$('#compare-dialog').addEventListener('close',cancelComparison);
$('#mobile-compare-models').addEventListener('click',openComparison);
$('#show-history').addEventListener('click',()=>openHistory().catch(error=>updateAnalysisError(error.message)));$('#history-model-filter').addEventListener('change',renderHistory);$('#history-status-filter').addEventListener('change',renderHistory);$('#export-history-json').addEventListener('click',()=>exportHistory('json'));$('#export-history-csv').addEventListener('click',()=>exportHistory('csv'));
$('#document-input').addEventListener('change',()=>importDocument().catch(error=>{$('#document-status').textContent=error.message}));document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>loadDemo(button.dataset.demo)));
