const panels={
  claims:`<div class="metric-row"><div><strong>2</strong><small>SUPPORTED</small></div><div><strong>0</strong><small>UNVERIFIED</small></div><div><strong>0</strong><small>CONTRADICTED</small></div></div><article class="claim-card"><small>SUPPORTED · CLAIM 1</small><p>A useful research answer identifies the passages used for its factual claims.</p><blockquote>“A research answer should identify its sources. Readers should be able to inspect the passage behind a claim.”</blockquote></article><article class="claim-card"><small>SUPPORTED · CLAIM 2</small><p>Missing evidence should be visible instead of presented as proof of truth.</p><blockquote>“Missing evidence should be clearly distinguished from conflicting evidence.”</blockquote></article>`,
  sources:`<article class="source-card"><small>ILLUSTRATIVE SOURCE · [1]</small><p><a href="https://github.com/Paila009/SOA">Grounded research handbook ↗</a></p><p>A research answer should identify its sources. Readers should be able to inspect the passage behind a claim. Missing evidence should be clearly distinguished from conflicting evidence.</p></article><p class="method-card">This is a hand-authored interface demonstration. The full application saves the actual passages retrieved for each answer.</p>`,
  method:`<article class="method-card"><p><strong>Answer model</strong><br>Illustrative example · not model-generated</p><p><strong>Review method</strong><br>Hand-authored demo of the saved evidence workflow</p><p><strong>Important limitation</strong><br>A text match is a screening signal. It does not establish source quality, factual truth, calibrated accuracy, causal validity, or hallucination-free output.</p></article>`
};
const panel=document.querySelector('#review-panel');
function show(name){panel.innerHTML=panels[name]||panels.claims;document.querySelectorAll('[data-panel]').forEach(button=>button.classList.toggle('active',button.dataset.panel===name));}
document.addEventListener('click',event=>{const button=event.target.closest('[data-panel],[data-tab]');if(!button)return;show(button.dataset.panel||button.dataset.tab);document.querySelector('.review').scrollIntoView({behavior:'smooth',block:'center'});});
show('claims');
